Also parse AND-joned list of author names (fix #18)
ropensci/bibtex pull request #22
Opened 2019-07-25 09:04 UTC by katrinleinweber

Besides this fix, I have a problem with `author = {LastName1, LastName2, LastName3}`-type of lists. Would adding `|,` into the `()`-group solve this?

2019-07-25 09:21 UTC, katrinleinweber commented
We could also switch to `perl = TRUE` & use `?i` in `rx`. I'm just not sure where exactly it needs to go. [Maybe](https://www.pcre.org/original/pcre.txt) into its own parentheses like `(?i)(and|AND)`?!?

2020-09-22 18:34 UTC, coatless requested changes
@katrinleinweber thanks for the patch! Sorry for the delay in reviewing the PR, rOpenSci has only recently adopted the package.

Let's aim to go the case insensitive route that you mentioned. I've sketched out a few suggested changes. Please feel free to merge into your PR as-needed.

Note to future-self: R's use of perl in regular expressions requires modifiers with `(?i)` at the front of the expression with `perl = TRUE` inside the relevant base _R_ regular expression function. 

``` r
rx <- "(?i)[[:space:]]+and[[:space:]]+"
x = c("First Last and Second Last", 
      "First Last AND Second Last",
      "First Last And Second Last"
      )
strsplit(x, rx, perl = TRUE)
#> [[1]]
#> [1] "First Last"  "Second Last"
#> 
#> [[2]]
#> [1] "First Last"  "Second Last"
#> 
#> [[3]]
#> [1] "First Last"  "Second Last"
```

2020-09-22 18:34 UTC, coatless commented on R/bibtex.R
> +  rx <- "[[:space:]]+(and|AND)[[:space:]]+"
```suggestion
  rx <- "(?i)[[:space:]]+and[[:space:]]+"
```

2020-09-22 18:34 UTC, coatless commented on R/bibtex.R
>    authors <- lapply(strsplit(x, rx)[[1]], ArrangeSingleAuthor)
```suggestion
  authors <- lapply(strsplit(x, rx, perl = TRUE)[[1]], ArrangeSingleAuthor)
```

2020-09-25 14:48 UTC, coatless approved these changes

2020-09-25 14:48 UTC, merged